### ISSUE TITLE
Rifampicin / AADAC / Kcat value from literature? 6.5 min(-1)?

### ISSUE THREAD

**Issue by MTHuisman** [Open-Systems-Pharmacology/ISSX-2017-Cologne#1]
While practising the Rifampicin/Midazolam DDI (ISSX-2017, [https://github.com/Open-Systems-Pharmacology/ISSX-2017-Cologne](url)), I went back to the publication fomr Nakajima 2011 (http://sci-hub.tw/10.1016/j.bcp.2011.08.003) to practise the calculation of their Vmax (162.6 pmol/min/mg and 140.7 pmol/min/mg).

MW of AADAC = 45734 Da
Unit of Kcat = min-1
That bring me to the following calculation:
Vmax = 140.7 pmol/min/mg = 140.7E-12 / min / 1 mg = 140.7E-12 / min / (1E-3/45734) =
140.7E-12/min/2.19E-8 = 0.0064 min-1

The value used in PK-Sim was 6.5 min-1

It seems that the value I calculated is 1000-fold different from the value in PK-Sim. 

Does anyone know where the difference comes from? I'm keen in understanding this, as I  need to be able to perfectly translate literature values to meaningful numbers in PK-Sim.

Thanking you in advance,
Maarten Huisman

**Comment by sfrechen** [comment]
Dear Maarten,

As we don't know anything about the total expression (reference concentration) of AADAC in the liver, we decided to fit the kcat. Thus, it is actually not comparable anymore. Out fitted kcat value is just valid assuming an arbitrary reference concentration of 1 µmol/L.

We just used the Km value of the source.

Sorry for any inconvenience.
Best
Sebastian

**Comment by MTHuisman** [comment]
Dear Sebastian,

Thank you for explaining this. That suggests that the relative abundance of AADAC is ~1:1000 in the _in vitro_ experiment of Nakajima (2011), as they measured total protein. That ratio seems reasonable. 

That explains it well, thank you, I'm on my way again!

Kind regards,
Maarten
